name: Update Views Badge

on:
  schedule:
    - cron: '0 0 * * *' # runs daily at midnight UTC
  workflow_dispatch:

jobs:
  update-views:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get traffic data
        run: |
          curl -H "Accept: application/vnd.github.v3+json" \
          -u ${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
          https://api.github.com/repos/${{ github.repository }}/traffic/views \
          > traffic.json

      - name: Generate views badge
        run: |
          COUNT=$(jq '.count' traffic.json)
          echo "![Views](https://img.shields.io/badge/Views-$COUNT-blue)" > views-badge.md

      - name: Commit badge
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add views-badge.md
          git commit -m "Update views badge"
          git push
